# Copyright 2024 Thomas. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.
# 

name: fmbb

repository:
  type: github
  origin: https://github.com/thomashoangvn/fvm_monorepo_bloc_boilerplate.git
  owner: thomashoangvn
  name: Flutter Monorepo BLoC Boilerplate

# Specifies to use fvm (Flutter Version Management) for the Flutter SDK.
sdkPath: .fvm/flutter_sdk

# Defines the project structure and the packages used in the workspace.
packages:
  - app
  - deps
  - design
  - features/**
  - infrastructure
  - widgetbook

command:
  version:
    # Restricts versioning to the main branch only.
    branch: main
    # Enables links to commits in the changelogs.
    linkToCommits: true
    # Creates a changelog for the entire workspace at the root level.
    workspaceChangelog: true

  bootstrap:
    environment:
      sdk: ">=3.8.1 <4.0.0"
      flutter: ">=3.32.2 <4.0.0"
    dependencies:
      # List of dependencies for the project.

    dev_dependencies:
      # List of dev dependencies used for generating code, metrics, etc.

    # Allows running `pub get` in parallel.
    runPubGetInParallel: true

    hooks:
      pre: melos clean
      post: melos generate && melos reset:ios

  clean:
    hooks:
      pre: melos reset

# Scripts for various tasks like cleaning, generating code, running tests, etc.
scripts:
  reset:
    description: Clean things very deeply by removing untracked files.
    run: |
      melos exec --flutter -c 1 -- "flutter clean"

  reset:ios:
    description: Clean ios pods to fix any pods related issues.
    run: |
      cd app/ios && \
      rm -Rf Pods 2>/dev/null || true && \
      rm Podfile.lock 2>/dev/null || true && \
      flutter precache --ios && \
      pod install --repo-update

  dart:check:
    description: Run `dart` checks for all packages.
    run: |
      melos format -c 6 --line-length 120 --set-exit-if-changed .
      melos analyze -c 6 --fatal-infos --fatal-warnings .

  dart:fix:
    description: Run `dart` fix for all packages.
    run: |
      melos exec -c 6 --ignore="*example*" -- \
      dart format -l 120 .
      dart analyze -fatal-infos --fatal-warnings .

  dcm:check:
    description: Run `dart code metrics` checks for all packages.
    run: |
      melos exec -c 6 --ignore="*example*" -- \
      dcm format -l 120 --dry-run .
      dcm analyze --fatal-style --fatal-performance --fatal-warnings .

  dcm:fix:
    description: Run `dart code metrics` fix for all packages.
    run: dcm fix -l 120 .

  generate:
    description: Generate codes for all packages.
    run:  |
      melos exec -c 1 --depends-on="build_runner" -- \
        dart run build_runner build -d

  generate:assets:
    description: Generate asset codes for all packages.
    run:  |
      melos exec -c 1 --depends-on="flutter_gen_runner" -- \
        dart run build_runner build -d

  # Tests
  test:
    description: Run all Flutter tests in this project.
    run: melos run test:select --no-select

  test:select:
    description: Run `flutter test` for selected packages.
    run: melos exec -c 1 -- flutter test
    packageFilters:
      dirExists: test

  test:coverage:
    description: Generate coverage for the selected package.
    run: |
      melos exec -c 4 --fail-fast -- \
        flutter test --coverage

  test:update-goldens:
    description: Re-generate all golden test files.
    run: melos exec -- "flutter test --update-goldens"
    packageFilters:
      dirExists: test

  # CI Scripts
  review:
    description: Review the codebase.
    run:  |
      ./tools/scripts/review.sh
  review:fix:
    description: Fix the codebase.
    run:  |
      melos dart:fix && \
      melos dcm:fix

  build:android:
    description: Build Android APK.
    run: ./tools/scripts/build_android.sh

  release:android:
    description: Release Android APK.
    run: ./tools/scripts/release_android.sh

  build:ios:
    description: Build iOS IPA.
    run: ./tools/scripts/build_ios.sh

  release:ios:
    description: Release iOS IPA.
    run: ./tools/scripts/release_ios.sh