name: fmbb
description: "Flutter Monorepo Bloc Boilerplate"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.5.3 <4.0.0'

dev_dependencies:
  dart_code_metrics_presets: ^2.16.0
  husky: ^0.1.7
  lint_staged: ^0.5.1
  melos: ^6.1.0

lint_staged:
  # Exclude generated Dart files globally
  '!**/*.g.dart': ignore

  # Apply commands to all Dart files in specified directories
  '**/*.dart': fvm dart format -l 120 --fix && dart analyze