name: deps
description: The dependencies of the flutter advanced boilerplate.
publish_to: none
version: 0.0.1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  adaptive_theme: ^3.6.0
  auto_route: ^9.2.2
  back_button_interceptor: ^7.0.3
  design:
    path: ../design
  dio: ^5.7.0
  dio_smart_retry: ^6.0.0
  envied: ^0.5.4+1
  feature_core:
    path: ../features/_core
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.4.1
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  hydrated_bloc: ^9.1.5
  infinite_scroll_pagination: ^4.0.0
  infrastructure:
    path: ../infrastructure
  injectable: ^2.4.4
  internet_connection_checker_plus: ^2.5.1
  intl: ^0.19.0
  lottie: ^3.1.2
  package_info_plus: ^8.0.2
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  reactive_forms: ^17.0.1
  slang: ^3.31.2
  slang_flutter: ^3.31.0
  styled_text: ^8.1.0
  talker_bloc_logger: ^4.4.1
  talker_dio_logger: ^4.4.1
  talker_flutter: ^4.4.1
  universal_html: ^2.2.4

dependency_overrides:
  flutter_secure_storage_web:
    git:
      url: https://github.com/fikretsengul/flutter_secure_storage.git
      path: flutter_secure_storage_web
      ref: develop

dev_dependencies:
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
