name: app_name
description: The main app of the flutter monorepo bloc boilerplate.
publish_to: none
version: 0.0.1+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  deps:
    path: ../deps
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - ../design/assets/icons/
    - ../design/assets/anims/
    - ../design/assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: ../design/assets/fonts/Inter/Inter-Black.ttf
          weight: 900
        - asset: ../design/assets/fonts/Inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: ../design/assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: ../design/assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: ../design/assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: ../design/assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: ../design/assets/fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: ../design/assets/fonts/Inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: ../design/assets/fonts/Inter/Inter-Thin.ttf
          weight: 100