name: infrastructure
description: The infrastructure of the flutter advanced boilerplate.
publish_to: none
version: 0.0.1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  deps:
    path: ../deps
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  json_annotation: ^4.9.0
  meta: ^1.15.0
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  dart_code_metrics_presets: ^2.16.0
  envied_generator: ^0.5.4+1
  freezed: ^2.5.7
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  slang_build_runner: ^3.31.0
